language = "c++"
time_limit = 1
memory_limit = "256 MiB"
testcase_dir = "problem/aplusb"
src = "code/aplusb/malicious-manyfiles.cc"
# our working directory is read-only, so fopen will return NULL and
# fprintf will crash immediately
expect = "RunError"
